# name : rushikesh dane

1. Write a Python Program to Add Two Matrices?





In [54]:
a = [[1,2,3],
     [3,4,5],
     [3,7,8]]
b =[[1,6,3],
    [7,9,0],
    [3,9,1]]

In [55]:
import numpy as np

In [56]:
np.add(a,b) # adding two marix

array([[ 2,  8,  6],
       [10, 13,  5],
       [ 6, 16,  9]])

2. Write a Python Program to Multiply Two Matrices?

In [57]:
np.multiply(a,b) # multiply two marix

array([[ 1, 12,  9],
       [21, 36,  0],
       [ 9, 63,  8]])

3. Write a Python Program to Transpose a Matrix?

In [58]:
np.transpose(a) # transpose of matrix

array([[1, 3, 3],
       [2, 4, 7],
       [3, 5, 8]])

4. Write a Python Program to Sort Words in Alphabetic Order?

In [59]:
import re
def sort(string):
    word_list = re.split("\s+",string)


    word_list.sort()
    alpahbatical_string = " ".join(word_list)
    return alpahbatical_string

In [60]:
sort("bla bla a fooo ")

' a bla bla fooo'

5. Write a Python Program to Remove Punctuation From a String?

In [61]:
def remove_pun(s):
    l= []
    for i in s:
        w = re.sub(r'[^\w\s]','',i)
        l.append(w)
    return "".join(l)

In [62]:
remove_pun("fldjfdf,0fj 0ekm0m,...fdlkjf/")

'fldjfdf0fj 0ekm0mfdlkjf'