# 1. write python program for matrix addition

In [1]:
A = [[1,2,3],
    [4,5,6],
    [7,8,9]]
B = [[10,8,3],
    [9,5,9],
    [7,8,9]]

c = [[0,0,0],
    [0,0,0],
    [0,0,0]]




In [2]:
# using numpy 

import numpy as np

X = np.array(A)
print(X)
print("  ")
Y = np.array(B)
print(Y)
print("  ")
addition = X + Y
print("addition of two matrix")
print(addition)
print("  ")
multiplication = X*Y
print("product of two matrix")
print(multiplication)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
  
[[10  8  3]
 [ 9  5  9]
 [ 7  8  9]]
  
addition of two matrix
[[11 10  6]
 [13 10 15]
 [14 16 18]]
  
product of two matrix
[[10 16  9]
 [36 25 54]
 [49 64 81]]


In [3]:
# credit - geekforgeeks
for i in range(len(A)):
    #print(A[0])
    #print(len(A[0]))
    for j in range(len(A[0])):
        c[i][j] = A[i][j] + B[i][j]
    print(c)
    #print(A[i][i])
    
for i in c:
    print(i)
    

[[11, 10, 6], [0, 0, 0], [0, 0, 0]]
[[11, 10, 6], [13, 10, 15], [0, 0, 0]]
[[11, 10, 6], [13, 10, 15], [14, 16, 18]]
[11, 10, 6]
[13, 10, 15]
[14, 16, 18]


In [4]:
#d = [map(sum, zip(*args)) for args in zip(A, B)]
#d

# 2.Write a Python Program to Multiply Two Matrices?


In [5]:
Write a Python Program to Multiply Two Matrices

SyntaxError: invalid syntax (<ipython-input-5-41a5d874c821>, line 1)

In [6]:
for i in range(len(A)):
    #print(A[0])
    #print(len(A[0]))
    for j in range(len(A[0])):
        c[i][j] = A[i][j] * B[i][j]
    #print(c)
    #print(A[i][i])
    
for i in c:
    print(i)

[10, 16, 9]
[36, 25, 54]
[49, 64, 81]


# 3.Write a Python Program to Transpose a Matrix?

In [7]:
import numpy as np

In [8]:
V = np.array([[2, 4], [5, -6],[4,7]])

In [9]:
V

array([[ 2,  4],
       [ 5, -6],
       [ 4,  7]])

# 4 Write a Python Program to Sort Words in Alphabetic Order?

In [10]:
n = input("enter anu string")
def sort(n):
    n= n.lower()
    words= n.split()
    #print(var1)
    words.sort()
    
    
    for word in words:
        print(word)
sort(n)

enter anu stringfrush dkjf epf fjjf
dkjf
epf
fjjf
frush


# 5 Write a Python Program to Remove Punctuation From a String?

In [11]:
string = "() kjfkljf , djflk ,_ , fi ,"

punc = '''!()-[]{};:'"\, <>./?@#$%^&*_~'''

for i in string :
    if i  in punc :
        string=string.replace(i," ")
        #print(i)
        
print(string)

    

   kjfkljf   djflk      fi  
