Question 1:
Write a program that calculates and prints the value according to the given formula:
Q = Square root of [(2 * C * D)/H]
Following are the fixed values of C and H:
C is 50. H is 30.
D is the variable whose values should be input to your program in a comma-separated
sequence.
Example
Let us assume the following comma separated input sequence is given to the program:
100,150,180
The output of the program should be:
18,22,24

In [30]:

def formula2(*args):
    C = 50
    H = 30
    import math
    A = []
    
    for i in args :
        A.append((2*C*i)/H)
    for i in A :
        print(round(math.sqrt(i)))
        
    

In [37]:
formula2(100,150,180)

18
22
24


 Question 2:
Write a program which takes 2 digits, X,Y as input and generates a 2-dimensional array. The
element value in the i-th row and j-th column of the array should be i*j.
Note: i=0,1.., X-1; j=0,1,¡Y-1.
Example
Suppose the following inputs are given to the program:
3,5
Then, the output of the program should be:
[[0, 0, 0, 0, 0], [0, 1, 2, 3, 4], [0, 2, 4, 6, 8]]

In [22]:
row_num = int(input("Input number of rows: "))
col_num = int(input("Input number of columns: "))
multi_list = [[0 for col in range(col_num)] for row in range(row_num)]

import numpy as np
a=np.zeros((row_num,col_num))
#print(a)

for row in range(row_num):
    for col in range(col_num):
        a[row][col]= row*col

print(a)

Input number of rows: 4
Input number of columns: 7
[[ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  1.  2.  3.  4.  5.  6.]
 [ 0.  2.  4.  6.  8. 10. 12.]
 [ 0.  3.  6.  9. 12. 15. 18.]]


Question 3:
Write a program that accepts a comma separated sequence of words as input and prints the

words in a comma-separated sequence after sorting them alphabetically.

Suppose the following input is supplied to the program:
    
without,hello,bag,world
Then, the output should be:
    
bag,hello,without,world

In [45]:
def sorting(*args):
    b = list(args)
    b.sort()
    for i in b:
        print(i,end= ",")

In [46]:
sorting('without','hello','bag','world')

bag,hello,without,world,

Q4Write a program that accepts a sequence of whitespace separated words as input and prints
the words after removing all duplicate words and sorting them alphanumerically.

Suppose the following input is supplied to the program:
hello world and practice makes perfect and hello world again

Then, the output should be:
again and hello makes perfect practice world

In [14]:
string  = input("enter your string ")

list1 = [ i for i in string.split(" ")]
b = (set(list1))
c = list(b)
c.sort()
for i in c:
    print(i,end=" ")


enter your string hello world and practice makes perfect and hello world again
 again and hello makes perfect practice world 

Question 5:

Write a program that accepts a sentence and calculate the number of letters and digits.

Suppose the following input is supplied to the program:
hello world! 123

Then, the output should be:
LETTERS 10

DIGITS 3

In [27]:
# credit :https://www.geeksforgeeks.org/python-program-to-calculate-the-number-of-digits-and-letters-in-a-string/
all_digits = ['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']
all_letters = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l',
               'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z']

str1 = input("enter your string")
l=0
d=0

for i in str1 :

    if i in all_letters :
        l = l+1
    
    
    elif i in all_digits :
        d = d+1
print(l)
print(d)

enter your stringhello world! 123
10
3


In [ ]:
"""string1  = input("enter your string")
count1 =0
for j in string1:
    
    if j.isalpha():
        count1 = count1 + 1
print(count1)"""

Q6 A website requires the users to input username and password to register. Write a program to
check the validity of password input by users.
Following are the criteria for checking the password:
    
1. At least 1 letter between [a-z]
2. At least 1 number between [0-9]
1. At least 1 letter between [A-Z]
3. At least 1 character from [$#@]
4. Minimum length of transaction password: 6
5. Maximum length of transaction password: 12
                              
Your program should accept a sequence of comma separated passwords and will check them
according to the above criteria. Passwords that match the criteria are to be printed, each
separated by a comma.
                              
Example
If the following passwords are given as input to the program:
ABd1234@1,a F1#,2w3E*,2We3345
Then, the output of the program should be:
ABd1234@1

In [54]:
"""password = input("enter you password")

all_digits = ['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']
all_letters = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l',
               'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z']
uppercase = str(all_letters).upper()
#print(uppercase)
symbol = ["$",'#','@']

for i in password:
    #print(len(password)
    
    if (len(password)<6 or len(password)>12):
        break
    elif str(i) not in all_letters:
    
        print(i)
    elif str(i) not in all_digits:
        
        print(i)
    elif str(i) not in uppercase:
        
        print(i)                    
    elif str(i) not in symbol:
        
        break 
    else:
        print("correct password")
        break
        """
        
    
    

'password = input("enter you password")\n\nall_digits = [\'0\', \'1\', \'2\', \'3\', \'4\', \'5\', \'6\', \'7\', \'8\', \'9\']\nall_letters = [\'a\', \'b\', \'c\', \'d\', \'e\', \'f\', \'g\', \'h\', \'i\', \'j\', \'k\', \'l\',\n               \'m\', \'n\', \'o\', \'p\', \'q\', \'r\', \'s\', \'t\', \'u\', \'v\', \'w\', \'x\', \'y\', \'z\']\nuppercase = str(all_letters).upper()\n#print(uppercase)\nsymbol = ["$",\'#\',\'@\']\n\nfor i in password:\n    #print(len(password)\n    \n    if (len(password)<6 or len(password)>12):\n        break\n    elif str(i) not in all_letters:\n    \n        print(i)\n    elif str(i) not in all_digits:\n        \n        print(i)\n    elif str(i) not in uppercase:\n        \n        print(i)                    \n    elif str(i) not in symbol:\n        \n        break \n    else:\n        print("correct password")\n        break\n        '

In [44]:
# credit :https://www.w3resource.com/python-exercises/python-conditional-exercise-15.php
import re
p= input("Input your password")
x = True
while x:  
    if (len(p)<6 or len(p)>12):
        break
    elif not re.search("[a-z]",p):
        break
    elif not re.search("[0-9]",p):
        break
    elif not re.search("[A-Z]",p):
        break
    elif not re.search("[$#@]",p):
        break
    elif re.search("\s",p):
        break
    else:
        print("Valid Password")
        x=False
        break

if x:
    print("Not a Valid Password")


Input your passwordABd1234@1,a F1#,2w3E*,2We3345 
Not a Valid Password
